name: build cassandra
on:
  workflow_dispatch:
  schedule:
    - cron: "50 0 * * 1"
  push:
    branches:
      - master
    paths:
      - cassandra/**
jobs:
  push:
    name: "yolks:cassandra_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - java8_python2
          - java11_python3
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: crpi-r97dq9ppddpijnzt.cn-chengdu.personal.cr.aliyuncs.com
          username: ${{ secrets.REPOSITORY_OWNER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./cassandra
          file: ./cassandra/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            crpi-r97dq9ppddpijnzt.cn-chengdu.personal.cr.aliyuncs.com/wapriaily/yolks:cassandra_${{ matrix.tag }}
