name: build mongodb
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "30 2 * * 1"
  push:
    branches:
      - master
    paths:
      - mongodb/**
jobs:
  push:
    name: "yolks:mongodb_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 4
          - 5
          - 6
          - 7
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: crpi-r97dq9ppddpijnzt.cn-chengdu.personal.cr.aliyuncs.com
          username: ${{ secrets.REPOSITORY_OWNER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./mongodb
          file: ./mongodb/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            crpi-r97dq9ppddpijnzt.cn-chengdu.personal.cr.aliyuncs.com/wapriaily/yolks:mongodb_${{ matrix.tag }}
